amp: true
anchor_ratios:
- 1.0
anchor_scale: 4
ann_dir: null
backbone_depth: 50
backbone_img_size: null
backbone_lr: 1.0e-05
backbone_name: convnextv2_base
backbone_out_channels: null
backbone_type: ConvNeXtV2Backbone
batch_size: 2
bbox_conv_out_channels: 256
bbox_head_type: Shared2FCBBoxHead
bbox_num_convs: 4
bbox_num_fcs: 2
bbox_num_shared_convs: 2
bbox_num_shared_fcs: 1
candidate_score_threshold: 0.03
cascade_bbox_weights:
- - 10.0
  - 10.0
  - 5.0
  - 5.0
- - 20.0
  - 20.0
  - 10.0
  - 10.0
- - 30.0
  - 30.0
  - 15.0
  - 15.0
cascade_iou_thresholds:
- 0.5
- 0.6
- 0.7
cascade_stage_weights:
- 1.0
- 0.5
- 0.25
cascade_target_stds:
- - 0.1
  - 0.1
  - 0.2
  - 0.2
- - 0.05
  - 0.05
  - 0.1
  - 0.1
- - 0.033
  - 0.033
  - 0.067
  - 0.067
coco_verbose: false
color_jitter: false
color_jitter_brightness: 0.3
color_jitter_contrast: 0.3
color_jitter_hue: 0.1
color_jitter_saturation: 0.3
copy_paste: false
copy_paste_prob: 0.5
crop_size_h: 1024
crop_size_w: 1024
data_dir: data
detector_type: CascadeRCNN
device: cuda:0
drop_path_rate: 0.1
elastic: false
elastic_prob: 0.1
epochs: 50
fc_out_channels: 1024
filter_empty_gt: true
fpn_num_outs: 5
fpn_out_channels: 256
freeze_stages: 0
grad_clip: 1.0
hflip_prob: 0.5
horizontal_flip: true
img_scale: 1024
log_dir: log/cascade_mask_rcnn
log_interval: 1000000000
log_level: WARNING
lr: 0.0001
mask_class_agnostic: false
mask_conv_to_res: true
mask_head_type: FCNMaskHead
mask_num_convs: 4
mask_size: 28
mask_threshold: 0.5
max_det: 300
min_gt_bbox_wh:
- 1
- 1
min_lr: 1.0e-06
min_size: 32
multiscale: true
nasfpn_stack_times: 1
neck_norm_cfg: null
neck_type: FPN
nms_threshold: 0.5
num_classes: 4
num_workers: 4
pad_val: 114
pretrained: true
rcnn_batch_size: 512
rcnn_ohem_loss_key: loss_cls
rcnn_positive_fraction: 0.25
rcnn_sampler_type: RandomSampler
reg_class_agnostic: true
resize_ratio_max: 2.0
resize_ratio_min: 0.5
resnet_frozen_stages: -1
roi_featmap_strides:
- 4
- 8
- 16
- 32
roi_out_size_bbox: 7
roi_out_size_mask: 14
rotate90: false
rpn_allowed_border: 0
rpn_batch_size: 256
rpn_neg_iou_thr: 0.3
rpn_nms_thresh: 0.45
rpn_pos_iou_thr: 0.7
rpn_positive_fraction: 0.5
rpn_post_nms_test: 1000
rpn_post_nms_train: 2000
rpn_pre_nms_test: 1000
rpn_pre_nms_train: 2000
rpn_strides:
- 4
- 8
- 16
- 32
- 64
save_dir: checkpoints/cascade_mask_rcnn
save_interval: 10
score_threshold: 0.05
seed: 42
val_interval: 1
val_ratio: 0.1
vertical_flip: true
vflip_prob: 0.5
wandb_project: none
warmup_epochs: 5
weight_decay: 0.05
work_dir: work_dirs/cascade_mask_rcnn
